### ISSUE TITLE
Please add some document

### ISSUE THREAD

**Issue by Himan000** [ConsenSys/gurvy#12]
Hi @rojotek @jmlubin @ggutoski @gbotrel @ThomasPiellard ，
gnark is wonderful project, but some code is hard to read if not all theory known by reader. Could anyone write some document/guide/api doc and provide some paper/blog/wiki link implement in gnark. Draft material is OK too. Thank you very much.

**Comment by Himan000** [comment]
@gbotrel ,
Could you add some document or do you have plan?

**Comment by gbotrel** [comment]
Hi @Himan000 ; please refer to the go doc : https://github.com/ConsenSys/gurvy#documentation 
For example, bn256: https://pkg.go.dev/github.com/consensys/gurvy/bn256#pkg-overview 

Documentation and tests will improve as we get closer to a v1.X.X release cycle.

**Comment by Himan000** [comment]
Hi @gbotrel ，
OK, I will try to read it though it's pithy. Looking forward to v1.X.X release.
Thanks.
