### ISSUE TITLE
Marshal/Unmarshal for G1 and G2 points

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ConsenSys/gurvy#16]
I noticed that the G1Jac, G1Affine, G2Jac and G2Affine have no way to marshal them from and to a byte array. 
Both the google and cloudflare implementations of bn256 have these methods as well as killic's implementation of bls12-381 (`FromBytes` and `ToBytes`). 
I would suggest to implement the marshaling as follows:
```
// Marshal
func (n *G1Jac) Marshal() []byte {}
	
// Unmarshal 
func (e *G1Jac) Unmarshal(m []byte) ([]byte, error) {}
``` 
Which is in line with the implementations of google and cloudflare used in go-ethereum and the golang bn256 implementation.

**Comment by MariusVanDerWijden** [comment]
I've wrote a little thingy here how I would envision the marshaling functions to look: 
https://github.com/MariusVanDerWijden/gurvy/tree/marshal
I just wrote into the auto generated code as a quick test

**Comment by MariusVanDerWijden** [comment]
That code is also wrong btw^^

**Comment by gbotrel** [comment]
Hi :-) -- this is work in progress, see branch feature/compress (not up to date with my local branch, few things missing). Will be merged to develop in few days.
