### ISSUE TITLE
Dependency management

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ConsenSys/gurvy#22]
Hey all, been trying to include gurvy's bn256 package into go-ethereum so it can be used in our differential fuzzing efforts. 
One problem I ran into is, that gurvy uses go-ethereum as a dependency for tests. This forces us to depend on an older version of go-ethereum which forces us to import older versions of the same packages we import the newest version from. E.g adding gurvy imports 5 additional versions of `golang.org/x/exp`. 

It would be great if you could move the tests from `bn256/interop_test.go` into another package.

See also https://github.com/ethereum/go-ethereum/pull/21812/files

edit. Removing go-ethereum from the codebase would reduce the `go.sum` file by 136 lines

**Comment by gbotrel** [comment]
fixed, moved interop_test files to `internal/interop`, project importing curves packages won't need to drag these test dependencies.
