### ISSUE TITLE
Question：which curve can be used for type-1 pairing implementation？

### ISSUE THREAD

**Issue by YinXinCryp** [ConsenSys/gurvy#31]
hi teams, I have a question for you guys. which curve can be used for type-1 pairing implementation？

any reply will be appreciated. thanks.

**Comment by yelhousni** [comment]
Hi @YinXinCryp, type-1 pairing uses supersingular elliptic curves. None is implemented in gurvy and I don't think there is an interest in doing that (at least for gurvy) as they are quite inefficient for 128-bit security (embedding degree k ≤ 6, and furthermore k ≤ 3 in characteristic not equal to 2 or 3).

**Comment by YinXinCryp** [comment]
@yelhousni  got it, thanks.
